name: Build mSearch

on:
  push:
    branches:
      - master   # âœ… ta vraie branche

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NODE_OPTIONS: --openssl-legacy-provider  # âš¡ fix OpenSSL 3

    steps:
      # ğŸ“¦ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # âš¡ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # ğŸ“¦ Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # â­ Build Webpack renderer & main
      - name: Build project
        run: yarn build

      # ğŸ” Package Electron
      - name: Package Electron app
        run: npx electron-builder -p always
