name: mSearch Build & Publish

on:
  push:
    branches:
      - master

jobs:
  release:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] # âŒ macOS supprimÃ©

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      # ğŸ“¦ Clone repo
      - uses: actions/checkout@v4

      # âš¡ Node 20 + cache Yarn
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # ğŸ”§ npm registry safe
      - run: yarn config set registry https://registry.npmjs.org

      # ğŸ“¦ install deps
      - run: yarn install --frozen-lockfile
        env:
          ADBLOCK: true

      # ğŸ python (node-gyp)
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # ğŸ” Build + Publish auto
      - name: Build & Publish
        run: npx cross-env NODE_OPTIONS=--openssl-legacy-provider electron-builder -p always
        shell: bash
