name: Build mSearch

on:
  push:
    branches:
      - master   # âœ… ta vraie branche

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      # ğŸ“¦ Clone
      - uses: actions/checkout@v4

      # âš¡ Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # ğŸ“¦ deps
      - run: yarn install --frozen-lockfile

      # â­ build webpack â†’ crÃ©e /build
      - run: yarn build

      # ğŸ” package electron
      - run: npx electron-builder -p always
